language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.1
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-android-21

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew connectedCheck -PdisablePreDex